name: Run script for management server

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted 
    steps:
      - name: Run the management server script
        run: |
          cd /home/avinash/scripts
          sudo bash managementServerScript.sh
